/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-7976c7d8afd785633bfb479e9cd673542daba37d
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NotificationSchemeAndProjectMappingJsonBean {
    #[serde(rename = "notificationSchemeId", skip_serializing_if = "Option::is_none")]
    pub notification_scheme_id: Option<String>,
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
}

impl NotificationSchemeAndProjectMappingJsonBean {
    pub fn new() -> NotificationSchemeAndProjectMappingJsonBean {
        NotificationSchemeAndProjectMappingJsonBean {
            notification_scheme_id: None,
            project_id: None,
        }
    }
}

